chore(deps-dev): bump jest and @types/jest in /assets (#683)
Bumps [jest](https://github.com/jestjs/jest/tree/HEAD/packages/jest) and [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/jest). These dependencies needed to be updated together.

Updates `jest` from 29.7.0 to 30.4.2
- [Release notes](https://github.com/jestjs/jest/releases)
- [Changelog](https://github.com/jestjs/jest/blob/main/CHANGELOG.md)
- [Commits](https://github.com/jestjs/jest/commits/v30.4.2/packages/jest)

Updates `@types/jest` from 29.5.14 to 30.0.0
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/jest)


Manual changes were required to finish the Jest v30 upgrade, as 
Dependabot could not complete it on it's own.

Upgrade `ts-jest` to a new minor version that supports Jest 30. There is
no `ts-jest` v30 at the time of this writing.

It uses Jest 30.3 instead of 30.4 (the latest as of this writing). Using
Jest 30.4 causes the following error message:
```
TypeError: this._moduleMocker.clearMocksOnScope is not a function
```
A fix for the above error has been implemented in Jest, but has not been
released at this time.

In newer versions of Jest, globals like `location` cannot be easily
mocked. Separate a call to `window.location.reload` into a separate
module, `windowHelper.ts`, so that the module containing the call can be
easily mocked.

Update various Jest assertion aliases that have been removed from the
library (e.g. `toBeCalled`) with their equivalent assertions.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Ryan Waskiewicz <rwaskiewicz@mbta.com>