chore: complete jest 30 update
This commit finishes the Jest v30 upgrade that Dependabot could not
complete on it's own.

Upgrade ts-jest to a new minor version that supports Jest 30. There is
no ts-jest v30 at the time of this writing.

It uses Jest 30.3 instead of 30.4 (the latest as of this writing). Using
Jest 30.4 causes the following error message:
```
TypeError: this._moduleMocker.clearMocksOnScope is not a function
```
A fix for the above error has been implemented in Jest, but has not been
released at this time.

In newer versions of Jest, globals like `location` cannot be easily
mocked. Separate a call to `window.location.reload` into a separate
module, `windowHelper.ts`, so that the module containing the call can be
easily mocked.

Update various Jest assertion aliases that have been removed from the
library (e.g. `toBeCalled`) with their equivalent assertions.